### ISSUE TITLE
Chinese display garbled code

### ISSUE THREAD

**Issue by Baikeryoyo** [PortSwigger/turbo-intruder#73] opened 2021-05-18 09:05 UTC
![image](https://user-images.githubusercontent.com/57838797/118623834-3479bd80-b7fb-11eb-9e2f-1ccc6416146f.png)

**Comment by albinowax** [comment] 2021-05-18 12:02
Dupe of https://github.com/PortSwigger/turbo-intruder/issues/67

**Closed** 2021-05-18 12:01 UTC

**Comment by Baikeryoyo** [comment] 2021-05-18 12:08
> [＃67的](https://github.com/PortSwigger/turbo-intruder/issues/67)重复[](https://github.com/PortSwigger/turbo-intruder/issues/67)

The problem has not been solved

**Comment by albinowax** [comment] 2021-05-19 08:35
I know, but having duplicate issues doesn't help
